/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppExercisesRouteImport } from './routes/_app.exercises'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as AppJoinCodeRouteImport } from './routes/_app.join.$code'
import { Route as AppListListIdRouteImport } from './routes/_app.list.$listId'
import { Route as AppNotesIndexRouteImport } from './routes/_app.notes.index'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app.notes.$noteId'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJoinCodeRoute = AppJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppListListIdRoute = AppListListIdRouteImport.update({
  id: '/list/$listId',
  path: '/list/$listId',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRoute,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/welcome': typeof WelcomeRoute
  '/exercises': typeof AppExercisesRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/s/$code': typeof SCodeRoute
  '/join/$code': typeof AppJoinCodeRoute
  '/list/$listId': typeof AppListListIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/notes/': typeof AppNotesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/welcome': typeof WelcomeRoute
  '/exercises': typeof AppExercisesRoute
  '/settings': typeof AppSettingsRoute
  '/s/$code': typeof SCodeRoute
  '/': typeof AppIndexRoute
  '/join/$code': typeof AppJoinCodeRoute
  '/list/$listId': typeof AppListListIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/notes': typeof AppNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/welcome': typeof WelcomeRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/notes': typeof AppNotesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/s/$code': typeof SCodeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/join/$code': typeof AppJoinCodeRoute
  '/_app/list/$listId': typeof AppListListIdRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/_app/notes/': typeof AppNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/welcome'
    | '/exercises'
    | '/notes'
    | '/settings'
    | '/s/$code'
    | '/join/$code'
    | '/list/$listId'
    | '/notes/$noteId'
    | '/api/webhooks/clerk'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/privacy'
    | '/welcome'
    | '/exercises'
    | '/settings'
    | '/s/$code'
    | '/'
    | '/join/$code'
    | '/list/$listId'
    | '/notes/$noteId'
    | '/api/webhooks/clerk'
    | '/notes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/privacy'
    | '/welcome'
    | '/_app/exercises'
    | '/_app/notes'
    | '/_app/settings'
    | '/s/$code'
    | '/_app/'
    | '/_app/join/$code'
    | '/_app/list/$listId'
    | '/_app/notes/$noteId'
    | '/api/webhooks/clerk'
    | '/_app/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  WelcomeRoute: typeof WelcomeRoute
  SCodeRoute: typeof SCodeRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/join/$code': {
      id: '/_app/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof AppJoinCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/list/$listId': {
      id: '/_app/list/$listId'
      path: '/list/$listId'
      fullPath: '/list/$listId'
      preLoaderRoute: typeof AppListListIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppNotesRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRoute
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJoinCodeRoute: typeof AppJoinCodeRoute
  AppListListIdRoute: typeof AppListListIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRoute,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppJoinCodeRoute: AppJoinCodeRoute,
  AppListListIdRoute: AppListListIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  WelcomeRoute: WelcomeRoute,
  SCodeRoute: SCodeRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
