/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppNotesIndexRouteImport } from './routes/_app.notes.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app.notes.$noteId'
import { Route as AppListListIdRouteImport } from './routes/_app.list.$listId'
import { Route as AppJoinCodeRouteImport } from './routes/_app.join.$code'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppListListIdRoute = AppListListIdRouteImport.update({
  id: '/list/$listId',
  path: '/list/$listId',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinCodeRoute = AppJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/s/$code': typeof SCodeRoute
  '/join/$code': typeof AppJoinCodeRoute
  '/list/$listId': typeof AppListListIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/notes/': typeof AppNotesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/s/$code': typeof SCodeRoute
  '/': typeof AppIndexRoute
  '/join/$code': typeof AppJoinCodeRoute
  '/list/$listId': typeof AppListListIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/notes': typeof AppNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_app/notes': typeof AppNotesRouteWithChildren
  '/s/$code': typeof SCodeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/join/$code': typeof AppJoinCodeRoute
  '/_app/list/$listId': typeof AppListListIdRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/notes/': typeof AppNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/welcome'
    | '/notes'
    | '/s/$code'
    | '/join/$code'
    | '/list/$listId'
    | '/notes/$noteId'
    | '/api/auth/$'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/welcome'
    | '/s/$code'
    | '/'
    | '/join/$code'
    | '/list/$listId'
    | '/notes/$noteId'
    | '/api/auth/$'
    | '/notes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/welcome'
    | '/_app/notes'
    | '/s/$code'
    | '/_app/'
    | '/_app/join/$code'
    | '/_app/list/$listId'
    | '/_app/notes/$noteId'
    | '/api/auth/$'
    | '/_app/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  SCodeRoute: typeof SCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/list/$listId': {
      id: '/_app/list/$listId'
      path: '/list/$listId'
      fullPath: '/list/$listId'
      preLoaderRoute: typeof AppListListIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/join/$code': {
      id: '/_app/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof AppJoinCodeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppNotesRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppRouteChildren {
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppJoinCodeRoute: typeof AppJoinCodeRoute
  AppListListIdRoute: typeof AppListListIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotesRoute: AppNotesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppJoinCodeRoute: AppJoinCodeRoute,
  AppListListIdRoute: AppListListIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  SCodeRoute: SCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
